spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: e-ticaret-kullanici
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379


jwt:
  secret: mysecretkeyucannotknowmetedayisimysecretkeyucannotknowmetedayisi
  expiration: 86400000
  refreshExpiration: 2592000000
